# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt-br

#  - name: RegexFeaturizer
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: False
    epochs: 100
  #- name: RegexEntityExtractor
  #  use_lookup_tables: True
  - name: FallbackClassifier
    threshold: 0.1
    ambiguity_threshold: 0.1
    #constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    model_confidence: softmax
    tensorboard_log_directory: ".tensorboard_ted"
    tensorboard_log_level: "epoch"
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: "utter_nao_core"
    enable_fallback_prediction: False
    constrain_similarities: true
#  - name: RulePolicy
#  - name: UnexpecTEDIntentPolicy
#    max_history: 5
#    epochs: 100
